
CREATE TABLE `A001_TABEVENTO` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_EVENTO` varchar(50) NOT NULL,
  `DESC_EVENTO` varchar(500) NOT NULL,
  `DESC_DATA` varchar(50) NOT NULL,
  `DESC_HORA` varchar(50) NOT NULL,
  `DESC_LOCAL` varchar(70) NOT NULL,
  `ATIVO` int(11) NOT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;