
CREATE TABLE `A001_TABEVENTO` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_EVENTO` varchar(50) NOT NULL,
  `DESC_EVENTO` varchar(500) NOT NULL,
  `DESC_DATA` varchar(50) NOT NULL,
  `DESC_HORA` varchar(50) NOT NULL,
  `DESC_LOCAL` varchar(70) NOT NULL,
  `ATIVO` int(11) NOT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `A002_TABTICKET` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `REL_EVENTO` int(11) NOT NULL,
  `REL_PAGAMENTO` int(11) NOT NULL,
  `NOME` varchar(100) NOT NULL,
  `CPF` varchar(30),
  `FONE` varchar(30),
  `EMAIL` varchar(100),
  `DATAHORA` varchar(30),
  `GEROU_PIX` int(11),
  `PAGOU` int(11),
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;